make buttons
js-tasks-ru/htmlcss-20231222_wowka pull request #4
Opened 2024-01-10 17:23 UTC by wowka4

2024-01-10 17:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-10 21:19 UTC, GSemikozov requested changes

2024-01-10 21:19 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +@import '../../assets/css/main.css';
на уровне компонента - ни в коем случае :) наоборот - все файлы стилей компонентов подключаем в main

2024-01-10 21:19 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +:root {
root описываем только в main

2024-01-10 21:19 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    margin: 0 10px;
марджины на уровне блока не задаем

2024-01-10 21:19 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    box-sizing: content-box;
лучше border-box

2024-01-10 21:19 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +
не хватает паддингов и стилей описания текста

2024-01-10 21:19 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.btn_primary:disabled {
это общее состояние для всех типов кнопок - .button:disabled

2024-01-10 21:19 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +                <div>
лишние элементы внутри кнопки - лишние в целом, а еще и неправильно используются - в button не валидно использовать div или p

2024-01-11 07:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-11 09:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-01-14 17:07 UTC, GSemikozov approved these changes

2024-01-14 17:07 UTC, merged